name: Buuld and upload artifacts

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build archlinux package
        uses: mijailr/arch-makepkg-action@1.0.0

      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: archlinux-ifstat-rs
          path: '*.zst'
