name: Buuld and upload artifacts

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Install dependencies
        run: |
          pacman -Suy --noconfirm --needed \
            base-devel

      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Build Arch Linux package
        run: makepkg --syncdeps --noconfirm

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: archlinux-ifstat-rs
          path: '*.zst'
